runtime: python
env: flex
entrypoint: python main.py

runtime_config:
  operating_system: ubuntu22
  runtime_version: "3.11"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
